[package]
name = "resolv"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.43", features = ["full", "rt-multi-thread"] }
hickory-resolver = "0.24"
anyhow = "1.0"
futures = "0.3"
reqwest = { version = "0.12.12", features = ["blocking"] }
indicatif = "0.17"
num_cpus = "1.16"
