use anyhow::Result;

#[derive(Debug, Clone)]
pub struct DnsProvider {
    pub name: String,
    pub organization: String,
    pub ipv4: String,
    pub ipv6: Option<String>,
    pub location: String,
    pub avg_response_time: Option<f64>,
}

pub async fn get_providers() -> Result<Vec<DnsProvider>> {
    Ok(vec![
        DnsProvider {
            name: "Google Public DNS".into(),
            organization: "Google".into(),
            ipv4: "8.8.8.8".into(),
            ipv6: Some("2001:4860:4860::8888".into()),
            location: "Worldwide (Anycast)".into(),
            avg_response_time: None,
        },
        DnsProvider {
            name: "Google Public DNS 2".into(),
            organization: "Google".into(),
            ipv4: "8.8.4.4".into(),
            ipv6: Some("2001:4860:4860::8844".into()),
            location: "Worldwide (Anycast)".into(),
            avg_response_time: None,
        },
        DnsProvider {
            name: "Cloudflare DNS".into(),
            organization: "Cloudflare".into(),
            ipv4: "1.1.1.1".into(),
            ipv6: Some("2606:4700:4700::1111".into()),
            location: "Worldwide (Anycast)".into(),
            avg_response_time: None,
        },
        DnsProvider {
            name: "Cloudflare DNS 2".into(),
            organization: "Cloudflare".into(),
            ipv4: "1.0.0.1".into(),
            ipv6: Some("2606:4700:4700::1001".into()),
            location: "Worldwide (Anycast)".into(),
            avg_response_time: None,
        },
        DnsProvider {
            name: "Quad9".into(),
            organization: "PCH/IBM".into(),
            ipv4: "9.9.9.9".into(),
            ipv6: Some("2620:fe::fe".into()),
            location: "Worldwide (Anycast)".into(),
            avg_response_time: None,
        },
        DnsProvider {
            name: "Quad9 Secondary".into(),
            organization: "PCH/IBM".into(),
            ipv4: "149.112.112.112".into(),
            ipv6: Some("2620:fe::9".into()),
            location: "Worldwide (Anycast)".into(),
            avg_response_time: None,
        },
        DnsProvider {
            name: "OpenDNS".into(),
            organization: "Cisco".into(),
            ipv4: "208.67.222.222".into(),
            ipv6: Some("2620:0:ccc::2".into()),
            location: "Worldwide (Anycast)".into(),
            avg_response_time: None,
        },
        DnsProvider {
            name: "OpenDNS 2".into(),
            organization: "Cisco".into(),
            ipv4: "208.67.220.220".into(),
            ipv6: Some("2620:0:ccd::2".into()),
            location: "Worldwide (Anycast)".into(),
            avg_response_time: None,
        },
        DnsProvider {
            name: "Level 3".into(),
            organization: "Level 3 Communications".into(),
            ipv4: "209.244.0.3".into(),
            ipv6: None,
            location: "Worldwide".into(),
            avg_response_time: None,
        },
        DnsProvider {
            name: "Level 3 Secondary".into(),
            organization: "Level 3 Communications".into(),
            ipv4: "209.244.0.4".into(),
            ipv6: None,
            location: "Worldwide".into(),
            avg_response_time: None,
        },
        DnsProvider {
            name: "Verisign DNS".into(),
            organization: "Verisign".into(),
            ipv4: "64.6.64.6".into(),
            ipv6: Some("2620:74:1b::1:1".into()),
            location: "Worldwide (Anycast)".into(),
            avg_response_time: None,
        },
        DnsProvider {
            name: "Verisign DNS 2".into(),
            organization: "Verisign".into(),
            ipv4: "64.6.65.6".into(),
            ipv6: Some("2620:74:1c::2:2".into()),
            location: "Worldwide (Anycast)".into(),
            avg_response_time: None,
        },
        DnsProvider {
            name: "DNS.WATCH".into(),
            organization: "DNS.WATCH".into(),
            ipv4: "84.200.69.80".into(),
            ipv6: Some("2001:1608:10:25::1c04:b12f".into()),
            location: "Germany".into(),
            avg_response_time: None,
        },
        DnsProvider {
            name: "DNS.WATCH 2".into(),
            organization: "DNS.WATCH".into(),
            ipv4: "84.200.70.40".into(),
            ipv6: Some("2001:1608:10:25::9249:d69b".into()),
            location: "Germany".into(),
            avg_response_time: None,
        },
        DnsProvider {
            name: "Yandex.DNS".into(),
            organization: "Yandex".into(),
            ipv4: "77.88.8.8".into(),
            ipv6: Some("2a02:6b8::feed:0ff".into()),
            location: "Russia/Eastern Europe".into(),
            avg_response_time: None,
        },
        DnsProvider {
            name: "Yandex.DNS 2".into(),
            organization: "Yandex".into(),
            ipv4: "77.88.8.1".into(),
            ipv6: Some("2a02:6b8:0:1::feed:0ff".into()),
            location: "Russia/Eastern Europe".into(),
            avg_response_time: None,
        },
    ])
}
